/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

public enum ConnectionState {
  IS_PENDING,
  IS_CONNECTING,
  IS_CONNECTED,
  IS_DISCONNECTING,
  IS_SILENTLY_DISCONNECTING,
  IS_DISCONNECTED,
  IS_NOT_CONNECTED
}

}
