/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

public enum OutOfBandIdentifiers {
  ID_NAT_ESTABLISH_UNIDIRECTIONAL,
  ID_NAT_ESTABLISH_BIDIRECTIONAL,
  ID_NAT_TYPE_DETECT,
  ID_ROUTER_2_REPLY_TO_SENDER_PORT,
  ID_ROUTER_2_REPLY_TO_SPECIFIED_PORT,
  ID_ROUTER_2_MINI_PUNCH_REPLY,
  ID_ROUTER_2_MINI_PUNCH_REPLY_BOUNCE,
  ID_XBOX_360_VOICE,
  ID_XBOX_360_GET_NETWORK_ROOM,
  ID_XBOX_360_RETURN_NETWORK_ROOM,
  ID_NAT_PING,
  ID_NAT_PONG
}

}
