/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

public enum RNSPerSecondMetrics {
  USER_MESSAGE_BYTES_PUSHED,
  USER_MESSAGE_BYTES_SENT,
  USER_MESSAGE_BYTES_RESENT,
  USER_MESSAGE_BYTES_RECEIVED_PROCESSED,
  USER_MESSAGE_BYTES_RECEIVED_IGNORED,
  ACTUAL_BYTES_SENT,
  ACTUAL_BYTES_RECEIVED,
  RNS_PER_SECOND_METRICS_COUNT
}

}
