/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

public enum UDPForwarderResult {
  UDPFORWARDER_FORWARDING_ALREADY_EXISTS,
  UDPFORWARDER_NO_SOCKETS,
  UDPFORWARDER_BIND_FAILED,
  UDPFORWARDER_INVALID_PARAMETERS,
  UDPFORWARDER_NOT_RUNNING,
  UDPFORWARDER_SUCCESS,
  UDPFORWARDER_RESULT_COUNT
}

}
