/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

public enum JoinTeamType {
  JOIN_ANY_AVAILABLE_TEAM,
  JOIN_SPECIFIC_TEAM,
  JOIN_NO_TEAM
}

}
