/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

public enum MultilistType {
  ML_UNORDERED_LIST,
  ML_STACK,
  ML_QUEUE,
  ML_ORDERED_LIST,
  ML_VARIABLE_DURING_RUNTIME
}

}
