/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

public enum PacketReliability {
  UNRELIABLE,
  UNRELIABLE_SEQUENCED,
  RELIABLE,
  RELIABLE_ORDERED,
  RELIABLE_SEQUENCED,
  UNRELIABLE_WITH_ACK_RECEIPT,
  RELIABLE_WITH_ACK_RECEIPT,
  RELIABLE_ORDERED_WITH_ACK_RECEIPT,
  NUMBER_OF_RELIABILITIES
}

}
