/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

public enum PublicKeyMode {
  PKM_INSECURE_CONNECTION,
  PKM_ACCEPT_ANY_PUBLIC_KEY,
  PKM_USE_KNOWN_PUBLIC_KEY,
  PKM_USE_TWO_WAY_AUTHENTICATION
}

}
