/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

using System;
using System.Runtime.InteropServices;

public class RakNetListCellPointer : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RakNetListCellPointer(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(RakNetListCellPointer obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~RakNetListCellPointer() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.delete_RakNetListCellPointer(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

    public Cell this[int index]  
    {  
        get   
        {
            return Get((uint)index); // use indexto retrieve and return another value.    
        }  
        set   
        {
            Replace(value, value, (uint)index, "Not used", 0);// use index and value to set the value somewhere.   
        }  
    }


    public Cell Get(uint position) 
    {   
	return GetHelper(position);
    }

    public Cell Pop()
    {
	return PopHelper();
    }


  public RakNetListCellPointer() : this(RakNetPINVOKE.new_RakNetListCellPointer__SWIG_0(), true) {
  }

  public RakNetListCellPointer(RakNetListCellPointer original_copy) : this(RakNetPINVOKE.new_RakNetListCellPointer__SWIG_1(RakNetListCellPointer.getCPtr(original_copy)), true) {
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public RakNetListCellPointer CopyData(RakNetListCellPointer original_copy) {
    RakNetListCellPointer ret = new RakNetListCellPointer(RakNetPINVOKE.RakNetListCellPointer_CopyData(swigCPtr, RakNetListCellPointer.getCPtr(original_copy)), false);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Push(Cell input, string file, uint line) {
    RakNetPINVOKE.RakNetListCellPointer_Push(swigCPtr, Cell.getCPtr(input), file, line);
  }

  public void Insert(Cell input, uint position, string file, uint line) {
    RakNetPINVOKE.RakNetListCellPointer_Insert__SWIG_0(swigCPtr, Cell.getCPtr(input), position, file, line);
  }

  public void Insert(Cell input, string file, uint line) {
    RakNetPINVOKE.RakNetListCellPointer_Insert__SWIG_1(swigCPtr, Cell.getCPtr(input), file, line);
  }

  public void Replace(Cell input, Cell filler, uint position, string file, uint line) {
    RakNetPINVOKE.RakNetListCellPointer_Replace__SWIG_0(swigCPtr, Cell.getCPtr(input), Cell.getCPtr(filler), position, file, line);
  }

  public void Replace(Cell input) {
    RakNetPINVOKE.RakNetListCellPointer_Replace__SWIG_1(swigCPtr, Cell.getCPtr(input));
  }

  public void RemoveAtIndex(uint position) {
    RakNetPINVOKE.RakNetListCellPointer_RemoveAtIndex(swigCPtr, position);
  }

  public void RemoveAtIndexFast(uint position) {
    RakNetPINVOKE.RakNetListCellPointer_RemoveAtIndexFast(swigCPtr, position);
  }

  public void RemoveFromEnd(uint num) {
    RakNetPINVOKE.RakNetListCellPointer_RemoveFromEnd__SWIG_0(swigCPtr, num);
  }

  public void RemoveFromEnd() {
    RakNetPINVOKE.RakNetListCellPointer_RemoveFromEnd__SWIG_1(swigCPtr);
  }

  public uint GetIndexOf(Cell input) {
    uint ret = RakNetPINVOKE.RakNetListCellPointer_GetIndexOf(swigCPtr, Cell.getCPtr(input));
    return ret;
  }

  public uint Size() {
    uint ret = RakNetPINVOKE.RakNetListCellPointer_Size(swigCPtr);
    return ret;
  }

  public void Clear(bool doNotDeallocateSmallBlocks, string file, uint line) {
    RakNetPINVOKE.RakNetListCellPointer_Clear(swigCPtr, doNotDeallocateSmallBlocks, file, line);
  }

  public void Preallocate(uint countNeeded, string file, uint line) {
    RakNetPINVOKE.RakNetListCellPointer_Preallocate(swigCPtr, countNeeded, file, line);
  }

  public void Compress(string file, uint line) {
    RakNetPINVOKE.RakNetListCellPointer_Compress(swigCPtr, file, line);
  }

  public Cell GetHelper(uint position) {
    IntPtr cPtr = RakNetPINVOKE.RakNetListCellPointer_GetHelper(swigCPtr, position);
    Cell ret = (cPtr == IntPtr.Zero) ? null : new Cell(cPtr, false);
    return ret;
  }

  public Cell PopHelper() {
    IntPtr cPtr = RakNetPINVOKE.RakNetListCellPointer_PopHelper(swigCPtr);
    Cell ret = (cPtr == IntPtr.Zero) ? null : new Cell(cPtr, false);
    return ret;
  }

}

}
