/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

public enum ReadyEventSystemStatus {
  RES_NOT_WAITING,
  RES_WAITING,
  RES_READY,
  RES_ALL_READY,
  RES_UNKNOWN_EVENT
}

}
