/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

public enum PluginReceiveResult {
  RR_STOP_PROCESSING_AND_DEALLOCATE = 0,
  RR_CONTINUE_PROCESSING,
  RR_STOP_PROCESSING
}

}
