/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

public enum StartupResult {
  RAKNET_STARTED,
  RAKNET_ALREADY_STARTED,
  INVALID_SOCKET_DESCRIPTORS,
  INVALID_MAX_CONNECTIONS,
  SOCKET_FAMILY_NOT_SUPPORTED,
  SOCKET_PORT_ALREADY_IN_USE,
  SOCKET_FAILED_TO_BIND,
  SOCKET_FAILED_TEST_SEND,
  PORT_CANNOT_BE_ZERO,
  FAILED_TO_CREATE_NETWORK_THREAD,
  COULD_NOT_GENERATE_GUID,
  STARTUP_OTHER_FAILURE
}

}
